require('./modules/animations')
require('./modules/cards')
require('./modules/text')
require('./modules/input')
require('./modules/orientation')
require('./modules/links')
require('./modules/confetti')
